name: Deploy HTML to Jenkins

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Jenkins for Deployment
        run: |
          curl -X POST "http://10.0.2.15:8080/job/HTML-Deploy/build?token=html-deploy-token" \
            --user "hari:11a9420ab71108bbbd36b757f79fd0f02e"
